#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'

check_git_repo() {
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        echo -e "${RED}Error: This is not a Git repository.${NO_COLOR}"
        exit 1
    fi
}

get_stale_cutoff() {
    echo -e "${YELLOW}Enter the number of weeks to consider branches as stale:${NO_COLOR}"
    read -r weeks
    if ! [[ "$weeks" =~ ^[0-9]+$ ]]; then
        echo -e "${RED}Error: Please enter a valid number of weeks.${NO_COLOR}"
        exit 1
    fi
    date -v-"$weeks"w +%s
}

get_stale_branches() {
    stale_branches=()
    for branchdata in $(git for-each-ref --format="%(refname:short)@%(committerdate:unix)" refs/heads/); do
        branch=$(echo "$branchdata" | cut -d '@' -f1)
        last_commit_time=$(echo "$branchdata" | cut -d '@' -f2)
        if [[ "$last_commit_time" =~ ^[0-9]+$ ]] && [ "$last_commit_time" -lt "$stale_cutoff" ]; then
            stale_branches+=("$branch")
        fi
    done
}
